"""
SES Email Service Module

Provides a clean interface for sending emails via AWS SES with templating support.
"""

import os
from typing import Any, Optional

import boto3  # type: ignore
from aws_lambda_powertools import Logger
from botocore.exceptions import ClientError  # type: ignore

logger = Logger(child=True)


class EmailService:
    """Service class for SES email operations."""

    # Base HTML email template
    BASE_EMAIL_TEMPLATE = """
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
            }}
            .header {{
                background-color: #f4f4f4;
                padding: 20px;
                text-align: center;
                border-bottom: 3px solid #007bff;
            }}
            .content {{
                padding: 20px;
                background-color: #ffffff;
            }}
            .footer {{
                padding: 15px;
                text-align: center;
                font-size: 12px;
                color: #666;
                background-color: #f4f4f4;
                margin-top: 20px;
            }}
            h1 {{
                color: #007bff;
                margin: 0;
            }}
            h2 {{
                color: #333;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{title}</h1>
        </div>
        <div class="content">
            {body}
        </div>
        <div class="footer">
            <p>Generated by AWS Lambda + SES</p>
            <p>Environment: {environment}</p>
        </div>
    </body>
    </html>
    """

    def __init__(self, from_email: Optional[str] = None, region_name: Optional[str] = None):
        """
        Initialize the email service.

        Args:
            from_email: Verified sender email address. If not provided, reads from
                       FROM_EMAIL environment variable.
            region_name: AWS region name. If not provided, uses default.
        """
        self.from_email = from_email or os.getenv("FROM_EMAIL")
        if not self.from_email:
            raise ValueError("From email must be provided or FROM_EMAIL env var must be set")

        # Initialize SES client
        client_kwargs = {}
        if region_name:
            client_kwargs["region_name"] = region_name
        self.ses_client = boto3.client("ses", **client_kwargs)

        logger.info(f"EmailService initialized with sender: {self.from_email}")

    def send_email(
        self,
        to_addresses: list[str],
        subject: str,
        body_html: str,
        body_text: Optional[str] = None,
        reply_to: Optional[list[str]] = None,
        cc_addresses: Optional[list[str]] = None,
        bcc_addresses: Optional[list[str]] = None,
    ) -> str:
        """
        Send an email via SES.

        Args:
            to_addresses: List of recipient email addresses
            subject: Email subject line
            body_html: HTML body content
            body_text: Plain text body content (optional, extracted from HTML if not provided)
            reply_to: Reply-to addresses (optional)
            cc_addresses: CC addresses (optional)
            bcc_addresses: BCC addresses (optional)

        Returns:
            SES Message ID

        Raises:
            ClientError: If email send fails
        """
        try:
            # Build destination
            destination: dict[str, list[str]] = {"ToAddresses": to_addresses}
            if cc_addresses:
                destination["CcAddresses"] = cc_addresses
            if bcc_addresses:
                destination["BccAddresses"] = bcc_addresses

            # Build message (SES API structure)
            message: dict[str, Any] = {
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {"Html": {"Data": body_html, "Charset": "UTF-8"}},
            }

            # Add plain text version if provided
            if body_text:
                message["Body"]["Text"] = {"Data": body_text, "Charset": "UTF-8"}

            # Send email
            send_kwargs: dict[str, Any] = {
                "Source": self.from_email,
                "Destination": destination,
                "Message": message,
            }

            if reply_to:
                send_kwargs["ReplyToAddresses"] = reply_to

            response = self.ses_client.send_email(**send_kwargs)

            message_id = response["MessageId"]
            logger.info(
                "Email sent successfully",
                extra={
                    "message_id": message_id,
                    "from": self.from_email,
                    "to": to_addresses,
                    "subject": subject,
                },
            )
            return message_id

        except ClientError as e:
            error_code = e.response["Error"]["Code"]
            error_message = e.response["Error"]["Message"]
            logger.error(
                f"Failed to send email: {error_code} - {error_message}",
                extra={
                    "from": self.from_email,
                    "to": to_addresses,
                    "error_code": error_code,
                },
            )
            raise

    def send_templated_email(
        self,
        to_addresses: list[str],
        subject: str,
        title: str,
        body_content: str,
        reply_to: Optional[list[str]] = None,
    ) -> str:
        """
        Send an email using the base template with injected content.

        Args:
            to_addresses: List of recipient email addresses
            subject: Email subject line
            title: Email title (shown in header)
            body_content: HTML content to inject into the body
            reply_to: Reply-to addresses (optional)

        Returns:
            SES Message ID

        Raises:
            ClientError: If email send fails
        """
        environment = os.getenv("ENVIRONMENT", "Dev")

        # Inject content into base template
        html_body = self.BASE_EMAIL_TEMPLATE.format(
            title=title, body=body_content, environment=environment
        )

        # Create plain text version (basic HTML stripping)
        text_body = f"{title}\n\n{body_content}\n\nGenerated by AWS Lambda + SES\nEnvironment: {environment}"

        return self.send_email(
            to_addresses=to_addresses,
            subject=subject,
            body_html=html_body,
            body_text=text_body,
            reply_to=reply_to,
        )

    def send_daily_report(
        self,
        to_addresses: list[str],
        report_content: Optional[str] = None,
    ) -> str:
        """
        Send a daily report email with default template.

        Args:
            to_addresses: List of recipient email addresses
            report_content: Optional custom report content (HTML)

        Returns:
            SES Message ID
        """
        environment = os.getenv("ENVIRONMENT", "Dev")
        subject = f"Daily Report - {environment} Environment"
        title = "Daily Report"

        # Default report content if none provided
        if report_content is None:
            report_content = """
                <h2>System Status</h2>
                <p>This is your scheduled daily email.</p>
                <p>All systems are operational.</p>

                <h3>Summary</h3>
                <ul>
                    <li>✅ Email service: Active</li>
                    <li>✅ Lambda function: Running</li>
                    <li>✅ Scheduled task: Executed</li>
                </ul>
            """

        return self.send_templated_email(
            to_addresses=to_addresses,
            subject=subject,
            title=title,
            body_content=report_content,
        )


# Singleton instance for reuse
_email_service: Optional[EmailService] = None


def get_email_service() -> EmailService:
    """
    Get or create a singleton EmailService instance.

    Returns:
        EmailService instance
    """
    global _email_service
    if _email_service is None:
        _email_service = EmailService()
    return _email_service
